/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMasterChef__factory } from "./IMasterChef__factory";
export { IOwnable__factory } from "./IOwnable__factory";
