/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IMasterChefV2, IMasterChefV2Interface } from "../IMasterChefV2";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "poolId",
        type: "uint256",
      },
    ],
    name: "lpToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "poolId",
        type: "uint256",
      },
    ],
    name: "poolInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint128",
            name: "accSushiPerShare",
            type: "uint128",
          },
          {
            internalType: "uint64",
            name: "lastRewardBlock",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "allocPoint",
            type: "uint64",
          },
        ],
        internalType: "struct IMasterChefV2.PoolInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IMasterChefV2__factory {
  static readonly abi = _abi;
  static createInterface(): IMasterChefV2Interface {
    return new utils.Interface(_abi) as IMasterChefV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMasterChefV2 {
    return new Contract(address, _abi, signerOrProvider) as IMasterChefV2;
  }
}
